<a href="https://colab.research.google.com/github/meenakshimeenuzz21/DSA-Class-Notes/blob/main/CaseStudy_Data_PreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Dataset Overview**

In [131]:
import pandas as pd
import numpy as np

In [132]:
import pandas as pd

In [133]:
df = pd.read_csv("/content/House_Pricing.csv")
df.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21613 non-null  int64
 1   Date House was Sold                        21613 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21613 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21604 non-null  float64
 6   Lot Area (in Sqft)                         21604 non-null  float64
 7   No of Floors                               21613 non-null  float64
 8   Waterfront View                            21613 non-null  object
 9   No of Times Visited                        2124 non-null   object
 10  Condition of the House                     21613 non-null  object
 11  Overall Grade                              21613 non-null  int64
 12  Area of the House from Basement (in Sqft)  21610 non-null  float64
 13  Basement Area (in Sqft)                    21613 non-null  int64
 14  Age of House (in Years)                    21613 non-null  int64
 15  Renovated Year                             21613 non-null  int64
 16  Zipcode                                    21612 non-null  float64
 17  Latitude                                   21612 non-null  float64
 18  Longitude                                  21612 non-null  float64
 19  Living Area after Renovation (in Sqft)     21612 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21613 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

In [135]:
df.shape

(21613, 21)

In [136]:
df.describe()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
count,2.161300e+04,2.160900e+04,21613.000000,21609.000000,21604.000000,2.160400e+04,21613.000000,21613.000000,21610.000000,21613.000000,21613.000000,21613.000000,21612.000000,21612.000000,21612.000000,21612.000000,21613.000000
mean,4.580302e+09,5.401984e+05,3.370842,2.114732,2079.931772,1.510776e+04,1.494309,7.623467,1788.344193,291.509045,46.994864,84.402258,98077.937766,47.560048,-122.213892,1986.538914,12768.455652
std,2.876566e+09,3.673890e+05,0.930062,0.770138,918.487597,4.142827e+04,0.539989,1.105439,827.982604,442.575043,29.373411,401.679240,53.505425,0.138565,0.140830,685.404255,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,1.000000,290.000000,0.000000,3.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1429.250000,5.040000e+03,1.000000,7.000000,1190.000000,0.000000,21.000000,0.000000,98033.000000,47.470975,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.617500e+03,1.500000,7.000000,1560.000000,0.000000,43.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068825e+04,2.000000,8.000000,2210.000000,560.000000,67.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,10.000000,9410.000000,4820.000000,118.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

**Duplicate Removal**

In [137]:
df.duplicated().sum()

np.int64(0)

In [138]:
df = df.drop_duplicates()

In [139]:
duplicate_columns = []

for i in range(len(df.columns)):
    for j in range(i+1, len(df.columns)):
        if df.iloc[:, i].equals(df.iloc[:, j]):
            duplicate_columns.append(df.columns[j])

duplicate_columns

df = df.drop(columns=duplicate_columns)

**Handling Missing Values**

In [140]:
df.isnull().sum()

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [141]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
df

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,No,NaN,...,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,No,NaN,...,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,NaN,...,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,No,NaN,...,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,NaN,...,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357

In [142]:
cat_cols = df.select_dtypes(include='object').columns
df

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,No,NaN,...,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,No,NaN,...,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,NaN,...,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,No,NaN,...,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,NaN,...,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357

In [143]:
from sklearn.impute import SimpleImputer

In [144]:
num_imputer = SimpleImputer(strategy='mean')

df[num_cols] = num_imputer.fit_transform(df[num_cols])
df

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7.129301e+09,14 October 2017,221900.0,3.0,1.00,1180.0,5650.0,1.0,No,NaN,...,7.0,1180.0,0.0,63.0,0.0,98178.0,47.5112,-122.257,1340.0,5650.0
1,6.414100e+09,14 December 2017,538000.0,3.0,2.25,2570.0,7242.0,2.0,No,NaN,...,7.0,2170.0,400.0,67.0,1991.0,98125.0,47.7210,-122.319,1690.0,7639.0
2,5.631500e+09,15 February 2016,180000.0,2.0,1.00,770.0,10000.0,1.0,No,NaN,...,6.0,770.0,0.0,85.0,0.0,98028.0,47.7379,-122.233,2720.0,8062.0
3,2.487201e+09,14 December 2017,604000.0,4.0,3.00,1960.0,5000.0,1.0,No,NaN,...,7.0,1050.0,910.0,53.0,0.0,98136.0,47.5208,-122.393,1360.0,5000.0
4,1.954401e+09,15 February 2016,510000.0,3.0,2.00,1680.0,8080.0,1.0,No,NaN,...,8.0,1680.0,0.0,31.0,0.0,98074.0,47.6168,-122.045,1800.0,7503.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,2.630000e+08,14 May 2017,360000.0,3.0,2.50,1530.0,1131.0,3.0,No,NaN,...,8.0,1530.0,0.0,9.0,0.0,98103.0,47.6993,-122.346,1530.0,1509.0
21609,6.600060e+09,15 February 2016,400000.0,4.0,2.50,2310.0,5813.0,2.0,No,NaN,...,8.0,2310.0,0.0,4.0,0.0,98146.0,47.5107,-122.362,1830.0,7200.0
21610,1.523300e+09,14 June 2017,402101.0,2.0,0.75,1020.0,1350.0,2.0,No,NaN,...,7.0,1020.0,0.0,9.0,0.0,98144.0,47.5944,-122.299,1020.0,2007.0
21611,2.913101e+08,15 January 2016,400000.0,3.0,2.50,1600.0,2388.0,2.0,No,NaN,...,8.0,1600.0,0.0,14.0,0.0,98027.0,47.5345,-122.069,1410.0,1287.0
21612,1.523300e+09,14 October 2017,325000.0,2.0,0.75,1020.0,1076.0,2.0,No,NaN,...,7.0,1020.0,0.0,10.0,0.0,98144.0,47.5941,-122.299,1020.0,1357.0

In [145]:
cat_imputer = SimpleImputer(strategy='most_frequent')
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])
df

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7.129301e+09,14 October 2017,221900.0,3.0,1.00,1180.0,5650.0,1.0,No,Twice,...,7.0,1180.0,0.0,63.0,0.0,98178.0,47.5112,-122.257,1340.0,5650.0
1,6.414100e+09,14 December 2017,538000.0,3.0,2.25,2570.0,7242.0,2.0,No,Twice,...,7.0,2170.0,400.0,67.0,1991.0,98125.0,47.7210,-122.319,1690.0,7639.0
2,5.631500e+09,15 February 2016,180000.0,2.0,1.00,770.0,10000.0,1.0,No,Twice,...,6.0,770.0,0.0,85.0,0.0,98028.0,47.7379,-122.233,2720.0,8062.0
3,2.487201e+09,14 December 2017,604000.0,4.0,3.00,1960.0,5000.0,1.0,No,Twice,...,7.0,1050.0,910.0,53.0,0.0,98136.0,47.5208,-122.393,1360.0,5000.0
4,1.954401e+09,15 February 2016,510000.0,3.0,2.00,1680.0,8080.0,1.0,No,Twice,...,8.0,1680.0,0.0,31.0,0.0,98074.0,47.6168,-122.045,1800.0,7503.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,2.630000e+08,14 May 2017,360000.0,3.0,2.50,1530.0,1131.0,3.0,No,Twice,...,8.0,1530.0,0.0,9.0,0.0,98103.0,47.6993,-122.346,1530.0,1509.0
21609,6.600060e+09,15 February 2016,400000.0,4.0,2.50,2310.0,5813.0,2.0,No,Twice,...,8.0,2310.0,0.0,4.0,0.0,98146.0,47.5107,-122.362,1830.0,7200.0
21610,1.523300e+09,14 June 2017,402101.0,2.0,0.75,1020.0,1350.0,2.0,No,Twice,...,7.0,1020.0,0.0,9.0,0.0,98144.0,47.5944,-122.299,1020.0,2007.0
21611,2.913101e+08,15 January 2016,400000.0,3.0,2.50,1600.0,2388.0,2.0,No,Twice,...,8.0,1600.0,0.0,14.0,0.0,98027.0,47.5345,-122.069,1410.0,1287.0
21612,1.523300e+09,14 October 2017,325000.0,2.0,0.75,1020.0,1076.0,2.0,No,Twice,...,7.0,1020.0,0.0,10.0,0.0,98144.0,47.5941,-122.299,1020.0,1357.0

In [146]:
df.isnull().sum()

ID                                           0
Date House was Sold                          0
Sale Price                                   0
No of Bedrooms                               0
No of Bathrooms                              0
Flat Area (in Sqft)                          0
Lot Area (in Sqft)                           0
No of Floors                                 0
Waterfront View                              0
No of Times Visited                          0
Condition of the House                       0
Overall Grade                                0
Area of the House from Basement (in Sqft)    0
Basement Area (in Sqft)                      0
Age of House (in Years)                      0
Renovated Year                               0
Zipcode                                      0
Latitude                                     0
Longitude                                    0
Living Area after Renovation (in Sqft)       0
Lot Area after Renovation (in Sqft)          0
dtype: int64

Missing values were identified using df.isnull().sum(). All numerical features with missing values were handled using mean imputation by replacing missing values with the mean of their respective columns. The categorical feature contained no missing values; therefore, no imputation was required.

**Scaling Numerical Variables**

In [147]:
df = pd.read_csv("/content/House_Pricing.csv")
df

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,No,NaN,...,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,No,NaN,...,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,NaN,...,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,No,NaN,...,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,NaN,...,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357

In [148]:
from sklearn.preprocessing import StandardScaler

In [149]:
target = "Sale Price"

scale_cols = [col for col in num_cols if col != target]

scaler = StandardScaler()

df[scale_cols] = scaler.fit_transform(df[scale_cols])

df.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,0.886146,14 October 2017,221900.0,-0.398737,-1.447478,-0.979820,-0.228298,-0.915427,No,NaN,...,-0.564013,-0.734748,-0.658681,0.544898,-0.210128,1.870176,-0.352533,-0.306110,-0.943318,-0.260715
1,0.637511,14 December 2017,538000.0,-0.398737,0.175645,0.533572,-0.189869,0.936506,No,NaN,...,-0.564013,0.460957,0.245141,0.681079,4.746678,0.879599,1.161593,-0.746368,-0.432658,-0.187868
2,0.365444,15 February 2016,180000.0,-1.473959,-1.447478,-1.426216,-0.123294,-0.915427,No,NaN,...,-1.468651,-1.229939,-0.658681,1.293892,-0.210128,-0.933343,1.283560,-0.135688,1.070139,-0.172375
3,-0.727656,14 December 2017,604000.0,0.676485,1.149518,-0.130578,-0.243988,-0.915427,No,NaN,...,-0.564013,-0.891759,1.397515,0.204446,-0.210128,1.085190,-0.283250,-1.271837,-0.914137,-0.284522
4,-0.912881,15 February 2016,510000.0,-0.398737,-0.148980,-0.435434,-0.169641,-0.915427,No,NaN,...,0.340626,-0.130856,-0.658681,-0.544548,-0.210128,-0.073597,0.409582,1.199288,-0.272165,-0.192849

In [150]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[num_cols] = scaler.fit_transform(df[num_cols])

df.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,0.720103,14 October 2017,0.019266,0.090909,0.12500,0.067170,0.003108,0.0,No,NaN,...,0.666667,0.097588,0.000000,0.521739,0.000000,0.893939,0.571498,0.217608,0.161934,0.005742
1,0.647853,14 December 2017,0.060721,0.090909,0.28125,0.172075,0.004072,0.4,No,NaN,...,0.666667,0.206140,0.082988,0.556522,0.988089,0.626263,0.908959,0.166113,0.222165,0.008027
2,0.568795,15 February 2016,0.013770,0.060606,0.12500,0.036226,0.005743,0.0,No,NaN,...,0.555556,0.052632,0.000000,0.713043,0.000000,0.136364,0.936143,0.237542,0.399415,0.008513
3,0.251157,14 December 2017,0.069377,0.121212,0.37500,0.126038,0.002714,0.0,No,NaN,...,0.666667,0.083333,0.188797,0.434783,0.000000,0.681818,0.586939,0.104651,0.165376,0.004996
4,0.197333,15 February 2016,0.057049,0.090909,0.25000,0.104906,0.004579,0.0,No,NaN,...,0.777778,0.152412,0.000000,0.243478,0.000000,0.368687,0.741354,0.393688,0.241094,0.007871

**Encoding Categorical Variables**

In [151]:
cat_cols = df.select_dtypes(include='object').columns

cat_cols

Index(['Date House was Sold', 'Waterfront View', 'No of Times Visited',
       'Condition of the House'],
      dtype='object')

In [152]:
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

df.head()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),...,Date House was Sold_15 March 2016,Date House was Sold_15 May 2016,Waterfront View_Yes,No of Times Visited_Once,No of Times Visited_Thrice,No of Times Visited_Twice,Condition of the House_Excellent,Condition of the House_Fair,Condition of the House_Good,Condition of the House_Okay
0,0.720103,0.019266,0.090909,0.12500,0.067170,0.003108,0.0,0.666667,0.097588,0.000000,...,False,False,False,False,False,False,False,True,False,False
1,0.647853,0.060721,0.090909,0.28125,0.172075,0.004072,0.4,0.666667,0.206140,0.082988,...,False,False,False,False,False,False,False,True,False,False
2,0.568795,0.013770,0.060606,0.12500,0.036226,0.005743,0.0,0.555556,0.052632,0.000000,...,False,False,False,False,False,False,False,True,False,False
3,0.251157,0.069377,0.121212,0.37500,0.126038,0.002714,0.0,0.666667,0.083333,0.188797,...,False,False,False,False,False,False,True,False,False,False
4,0.197333,0.057049,0.090909,0.25000,0.104906,0.004579,0.0,0.777778,0.152412,0.000000,...,False,False,False,False,False,False,False,True,False,False

**Outlier Removal**

In [153]:
for col in scale_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower) & (df[col] <= upper)]

df.shape

(15084, 37)

In [154]:
num_cols = df.select_dtypes(include=np.number).columns

num_cols = num_cols.drop('Sale Price')

for col in num_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower) & (df[col] <= upper)]

df.shape

(14337, 37)

**Train-Test Split**

In [169]:
X = df.drop('Sale Price', axis=1)

y = df['Sale Price']

In [171]:
X.columns

Index(['ID', 'No of Bedrooms', 'No of Bathrooms', 'Flat Area (in Sqft)',
       'Lot Area (in Sqft)', 'No of Floors', 'Overall Grade',
       'Area of the House from Basement (in Sqft)', 'Basement Area (in Sqft)',
       'Age of House (in Years)', 'Renovated Year', 'Zipcode', 'Latitude',
       'Longitude', 'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)',
       'Date House was Sold_14 December 2017',
       'Date House was Sold_14 July 2017', 'Date House was Sold_14 June 2017',
       'Date House was Sold_14 May 2017',
       'Date House was Sold_14 November 2017',
       'Date House was Sold_14 October 2017',
       'Date House was Sold_14 September 2017',
       'Date House was Sold_15 April 2016',
       'Date House was Sold_15 February 2016',
       'Date House was Sold_15 January 2016',
       'Date House was Sold_15 March 2016', 'Date House was Sold_15 May 2016',
       'Waterfront View_Yes', 'No of Times Visited_Once',
       'No of Times Visited_Thrice', 'No of Times Visited_Twice',
       'Condition of the House_Excellent', 'Condition of the House_Fair',
       'Condition of the House_Good', 'Condition of the House_Okay'],
      dtype='object')

In [172]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [173]:
x_train.shape, x_test.shape
y_train.shape, y_test.shape

((11469,), (2868,))

In [159]:
x_train.shape

(11469, 36)

In [160]:
x_test.shape

(2868, 36)

In [161]:
y_train.shape

(11469,)

In [174]:
y_test.shape

(2868,)