<a href="https://colab.research.google.com/github/meenakshimeenuzz21/DSA-Class-Notes/blob/main/DATA_ACQUISITION_CASE_STUDY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries

In [ ]:
import pandas as pd
import sqlite3

Read CSV File

In [ ]:
population = pd.read_csv("population[1].csv")
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

Shape & Data Types

In [ ]:
population.shape

(25, 2)

In [ ]:
population.dtypes

country       object
population     int64
dtype: object

Task - 2 Read GDP Excel File

In [ ]:
gdp = pd.read_excel("/content/gdp[1].xlsx")

gdp.head()

         Country       GDP
0  United States  30500000
1          China  19230000
2          India   4187000
3          Japan   4180000
4        Germany   4744000

Column Names

In [ ]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

Data Types

In [ ]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

TASK - 3 Read JSON File

In [ ]:
internet = pd.read_json("/content/internet_users[1].json")
internet.head()

         country  internet_users
0  United States       312000000
1          China      1080000000
2          India       850000000
3          Japan       118000000
4        Germany        79000000

TASK - 4 Read XML File

In [ ]:
literacy = pd.read_xml("/content/literacy_rate[1].xml")
literacy.head()

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

Explore All Datasets

Part B – Data Understanding
Task 5

Explore each dataset.

Find the following:

● Number of rows

● Number of columns

● Column names

● Data types

● Missing values

● Duplicate records

In [ ]:
print("Population Dataset")
print("Shape:", population.shape)
print("Rows:", population.shape[0])
print("Columns:", population.shape[1])
print("Column Names:")
print(population.columns)
print("Data Types:")
print(population.dtypes)
print("Missing Values:")
print(population.isnull().sum())
print("Duplicate Records:", population.duplicated().sum())

Population Dataset
Shape: (25, 2)
Rows: 25
Columns: 2
Column Names:
Index(['country', 'population'], dtype='object')
Data Types:
country       object
population     int64
dtype: object
Missing Values:
country       0
population    0
dtype: int64
Duplicate Records: 0

Part C – Data Transformation

Task 6

Rename columns wherever necessary so that all datasets have a common column

name for merging.

Hint:

● Example: Country → country

In [ ]:
population.rename(columns={
    "Country": "country"
}, inplace=True)
population.head()
gdp.rename(columns={
    "Country": "country"
}, inplace=True)
gdp.head()
internet.rename(columns={
    "Country": "country"
}, inplace=True)
internet.head()
literacy.rename(columns={
    "Country": "country"
}, inplace=True)
literacy.head()
print(population.columns)
print(gdp.columns)
print(internet.columns)
print(literacy.columns)

Index(['country', 'population'], dtype='object')
Index(['country', 'GDP'], dtype='object')
Index(['country', 'internet_users'], dtype='object')
Index(['name', 'literacy_rate'], dtype='object')

Task 7 – Convert Numeric Columns

In [ ]:
population["population"] = pd.to_numeric(population["population"])
gdp["GDP"] = pd.to_numeric(gdp["GDP"])
internet["internet_users"] = pd.to_numeric(internet["internet_users"])
literacy["literacy_rate"] = pd.to_numeric(literacy["literacy_rate"])

Task 8 – Merge All Datasets

In [ ]:
data = population.merge(gdp,on="country")
data = data.merge(internet,on="country")
data = data.merge(literacy, left_on="country", right_on="name")
data.drop(columns=["name"], inplace=True)
data.head()

         country  population       GDP  internet_users  literacy_rate
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

Task 9 – Calculated Columns

Internet Penetration

In [ ]:
data["internet_penetration"] = (
    data["internet_users"] /
    data["population"]
)*100

GDP Per Capita

In [ ]:
data["gdp_per_capita"] = (
    data["GDP"] /
    data["population"]
)

Round

In [ ]:
data["internet_penetration"] = data["internet_penetration"].round(2)
data["gdp_per_capita"] = data["gdp_per_capita"].round(2)

Part- D --> Load Data

Task 10 – Store in SQLite

In [ ]:
conn = sqlite3.connect("country.db")
data.to_sql(
    "country_statistics",
    conn,
    if_exists="replace",
    index=False
)

25

Task 11 – Verify Database

In [ ]:
pd.read_sql(
    "SELECT * FROM country_statistics LIMIT 5",
    conn
)

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

Part -E

Data Analysis using Pandas

In [ ]:
data.sort_values(
    "GDP",
    ascending=False
).head(5)

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03

 Top 5 Population

In [ ]:
data.sort_values(
    "population",
    ascending=False
).head(5)

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.01

 Average Literacy Rate

In [ ]:
data["literacy_rate"].mean()

np.float64(97.248)

Literacy > 90%

In [ ]:
data[
    data["literacy_rate"] > 90
]

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
6,France,65273511,3211000,62000000,99.0,94.98,0.05
7,Italy,60461826,2420000,56000000,99.0,92.62,0.04
8,Canada,38005238,2250000,36000000,99.0,94.72,0.06
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
11,Russia,145934462,2200000,125000000,99.7,85.65,0.02
12,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
13,Spain,46754778,1710000,44000000,98.6,94.11,0.04
14,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
17,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
18,South Africa,59308690,410000,43000000,95.0,72.50,0.01
19,Argentina,45195774,640000,41000000,99.1,90.72,0.01
20,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
22,Sweden,10353442,650000,10100000,99.0,97.55,0.06
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09

### Countries with Internet Penetration > 70%

In [ ]:
data[
    data["internet_penetration"] > 70
]

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
6,France,65273511,3211000,62000000,99.0,94.98,0.05
7,Italy,60461826,2420000,56000000,99.0,92.62,0.04
8,Canada,38005238,2250000,36000000,99.0,94.72,0.06
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
11,Russia,145934462,2200000,125000000,99.7,85.65,0.02
12,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
13,Spain,46754778,1710000,44000000,98.6,94.11,0.04
14,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
17,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
18,South Africa,59308690,410000,43000000,95.0,72.50,0.01
19,Argentina,45195774,640000,41000000,99.1,90.72,0.01
20,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
22,Sweden,10353442,650000,10100000,99.0,97.55,0.06
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09

Top 5 GDP Per Capita

In [ ]:
data.sort_values(
    "gdp_per_capita",
    ascending=False
).head(5)

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07

Total Population

In [ ]:
data["population"].sum()

np.int64(4720039725)

Average Internet Penetration

In [ ]:
data["internet_penetration"].mean()

np.float64(89.6596)

Highest Internet Users

In [ ]:
data.sort_values(
    "internet_users",
    ascending=False
).head(1)

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
1,China,1411778724,19230000,1080000000,97.2,76.5,0.01

Correlation

In [ ]:
data["literacy_rate"].corr(
    data["internet_penetration"]
)

np.float64(0.77279756813985)

Part -F

Data Analysis using SQL

In [ ]:
pd.read_sql(
    "SELECT * FROM country_statistics ORDER BY GDP DESC LIMIT 5",
    conn
)

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,Germany,83240525,4744000,79000000,99.0,94.91,0.06
3,India,1380004385,4187000,850000000,77.7,61.59,0.00
4,Japan,125836021,4180000,118000000,99.0,93.77,0.03

In [ ]:
pd.read_sql(
    "SELECT AVG(literacy_rate) FROM country_statistics",
    conn
)

   AVG(literacy_rate)
0              97.248

In [ ]:
pd.read_sql(
    "SELECT * FROM country_statistics WHERE literacy_rate > 90",
    conn
)

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,Japan,125836021,4180000,118000000,99.0,93.77,0.03
3,Germany,83240525,4744000,79000000,99.0,94.91,0.06
4,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
5,France,65273511,3211000,62000000,99.0,94.98,0.05
6,Italy,60461826,2420000,56000000,99.0,92.62,0.04
7,Canada,38005238,2250000,36000000,99.0,94.72,0.06
8,Australia,25687041,1880000,24000000,99.0,93.43,0.07
9,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
10,Russia,145934462,2200000,125000000,99.7,85.65,0.02
11,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
12,Spain,46754778,1710000,44000000,98.6,94.11,0.04
13,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
14,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
15,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
16,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
17,South Africa,59308690,410000,43000000,95.0,72.50,0.01
18,Argentina,45195774,640000,41000000,99.1,90.72,0.01
19,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
20,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
21,Sweden,10353442,650000,10100000,99.0,97.55,0.06
22,Norway,5421241,580000,5300000,100.0,97.76,0.11
23,Singapore,5850342,530000,5600000,97.5,95.72,0.09

In [ ]:
pd.read_sql(
    "SELECT * FROM country_statistics ORDER BY internet_penetration DESC LIMIT 5;",
    conn
)

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
1,Norway,5421241,580000,5300000,100.0,97.76,0.11
2,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
3,Sweden,10353442,650000,10100000,99.0,97.55,0.06
4,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07

In [ ]:
pd.read_sql(
    "SELECT SUM(population) FROM country_statistics;",
    conn
)

   SUM(population)
0       4720039725

In [ ]:
data.nlargest(1, "gdp_per_capita")

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11

In [ ]:
data.to_csv(
    "final_country_statistics.csv",
    index=False
)
print("CSV file exported successfully.")

CSV file exported successfully.

In [ ]:
top10 = data.sort_values(
    by="gdp_per_capita",
    ascending=False
)
top10.head(10)

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07
20,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06
8,Canada,38005238,2250000,36000000,99.0,94.72,0.06
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
22,Sweden,10353442,650000,10100000,99.0,97.55,0.06

ETL Process Summary

1. Data Sources Used

Data was collected from four different file formats: CSV (Population), Excel (GDP), JSON (Internet Users), and XML (Literacy Rate).

2. Data Cleaning Steps

Each dataset was explored to identify rows, columns, data types, missing values, and duplicate records. Column names were standardized, and numeric columns were converted to the appropriate data types.

3. Transformations Performed

The datasets were merged using the common country column. New fields such as Internet Penetration (%) and GDP per Capita were calculated for analysis.

4. Database Loading Process

The final merged dataset was stored in a SQLite database using Pandas to_sql() function. The processed dataset was also exported as a CSV file.

5. Key Insights Obtained

The analysis identified the countries with the highest GDP, largest population, highest GDP per capita, and highest internet penetration. It also calculated the average literacy rate and total population, providing useful insights into global development indicators.

6. Conclusion

The ETL process successfully extracted data from multiple sources, transformed it into a consistent format, and loaded it into a database for efficient analysis and reporting.