<a href="https://colab.research.google.com/github/meenakshimeenuzz21/DSA-Class-Notes/blob/main/ETL_PRODUCT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EXTRACT

In [ ]:
import pandas as pd
import os
import shutil

def extract():

    os.makedirs("/content/raw_data", exist_ok=True)

    df = pd.read_csv("/content/EV_Charging_Grid_Load_Dataset_5000.csv")

    print("Number of Records:", df.shape[0])
    print("Number of Columns:", df.shape[1])

    shutil.copy(
        "/content/EV_Charging_Grid_Load_Dataset_5000.csv",
        "/content/raw_data/EV_Charging_Grid_Load_Dataset_5000.csv"
    )

    print("Raw data saved successfully!")

    return df


data = extract()

Number of Records: 5000
Number of Columns: 8
Raw data saved successfully!

In [ ]:
data.head()

,Station_ID,City,Charger_Type,Vehicle_Type,Energy_Consumed_kWh,Grid_Load_kW,Station_Status,Date
0,EV10001,Kochi,Fast,Bus,189.50,333.67,Active,2025-09-19
1,EV10002,Calicut,DC Fast,Bus,112.87,473.04,Active,2025-01-28
2,EV10003,Trivandrum,DC Fast,Car,135.41,242.44,Active,2025-05-27
3,EV10004,Hyderabad,DC Fast,Car,33.96,477.68,Active,2025-05-25
4,EV10005,Kochi,Level 2,Car,185.51,300.70,Active,2025-12-30

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Station_ID           5000 non-null   object
 1   City                 5000 non-null   object
 2   Charger_Type         5000 non-null   object
 3   Vehicle_Type         5000 non-null   object
 4   Energy_Consumed_kWh  5000 non-null   float64
 5   Grid_Load_kW         5000 non-null   float64
 6   Station_Status       5000 non-null   object
 7   Date                 5000 non-null   object
dtypes: float64(2), object(6)
memory usage: 312.6+ KB

In [ ]:
df.describe()

       Energy_Consumed_kWh  Grid_Load_kW
count          5000.000000   5000.000000
mean            130.214902    257.577314
std              69.730802    138.214749
min              10.050000     20.020000
25%              70.840000    136.202500
50%             129.700000    255.625000
75%             191.182500    376.060000
max             249.990000    499.990000

In [ ]:
df.shape

(5000, 8)

TRANSFORM

In [ ]:
df.isnull().sum()

Station_ID             0
City                   0
Charger_Type           0
Vehicle_Type           0
Energy_Consumed_kWh    0
Grid_Load_kW           0
Station_Status         0
Date                   0
dtype: int64

In [ ]:
df = df.drop_duplicates()

In [ ]:
df = df.fillna("Unknown")

In [ ]:
print(df.shape[0])

5000

In [ ]:
df["City"] = df["City"].str.title()
df

,Station_ID,City,Charger_Type,Vehicle_Type,Energy_Consumed_kWh,Grid_Load_kW,Station_Status,Date
0,EV10001,Kochi,Fast,Bus,189.50,333.67,Active,2025-09-19
1,EV10002,Calicut,DC Fast,Bus,112.87,473.04,Active,2025-01-28
2,EV10003,Trivandrum,DC Fast,Car,135.41,242.44,Active,2025-05-27
3,EV10004,Hyderabad,DC Fast,Car,33.96,477.68,Active,2025-05-25
4,EV10005,Kochi,Level 2,Car,185.51,300.70,Active,2025-12-30
...,...,...,...,...,...,...,...,...
4995,EV14996,Calicut,Level 2,Car,126.08,179.27,Active,2025-12-16
4996,EV14997,Trivandrum,Fast,Bus,47.20,377.78,Inactive,2025-05-14
4997,EV14998,Hyderabad,Slow,Car,172.31,167.83,Inactive,2025-09-04
4998,EV14999,Chennai,Fast,Bike,16.55,250.91,Inactive,2025-07-17
4999,EV15000,Calicut,Level 2,Bus,117.57,394.14,Inactive,2025-08-06

In [ ]:
df['Charger_Type'].value_counts()

Charger_Type
Level 2    1259
Slow       1255
Fast       1244
DC Fast    1242
Name: count, dtype: int64

In [ ]:
df['City'].value_counts()

City
Kochi         651
Bengaluru     645
Trivandrum    639
Mumbai        637
Chennai       628
Delhi         603
Hyderabad     602
Calicut       595
Name: count, dtype: int64

In [ ]:
df.head(10).to_csv(
    "reports/top10_records.csv",
    index=False
)

CLEAN DATASET

In [ ]:
df.to_csv(
    "reports/cleaned_dataset.csv",
    index=False
)

LOAD

In [ ]:
df.to_csv(
    "reports/cleaned_dataset.csv",
    index=False
)

In [ ]:
from google.colab import files

files.download(
    "reports/cleaned_dataset.csv"
)

In [ ]:
df.to_csv("EV_Charging_Stations_Cleaned.csv", index=False)
df

,Station_ID,City,Charger_Type,Vehicle_Type,Energy_Consumed_kWh,Grid_Load_kW,Station_Status,Date
0,EV10001,Kochi,Fast,Bus,189.50,333.67,Active,2025-09-19
1,EV10002,Calicut,DC Fast,Bus,112.87,473.04,Active,2025-01-28
2,EV10003,Trivandrum,DC Fast,Car,135.41,242.44,Active,2025-05-27
3,EV10004,Hyderabad,DC Fast,Car,33.96,477.68,Active,2025-05-25
4,EV10005,Kochi,Level 2,Car,185.51,300.70,Active,2025-12-30
...,...,...,...,...,...,...,...,...
4995,EV14996,Calicut,Level 2,Car,126.08,179.27,Active,2025-12-16
4996,EV14997,Trivandrum,Fast,Bus,47.20,377.78,Inactive,2025-05-14
4997,EV14998,Hyderabad,Slow,Car,172.31,167.83,Inactive,2025-09-04
4998,EV14999,Chennai,Fast,Bike,16.55,250.91,Inactive,2025-07-17
4999,EV15000,Calicut,Level 2,Bus,117.57,394.14,Inactive,2025-08-06

In [ ]:
from google.colab import files

files.download("EV_Charging_Stations_Cleaned.csv")

In [ ]:
def run_etl_pipeline():

    df = extract()

    df = df.drop_duplicates()

    df = df.fillna("Unknown")

    df["City"] = df["City"].str.title()

    df.to_csv("reports/cleaned_dataset.csv",index=False)

    df.head(10).to_csv("reports/top10_records.csv",index=False)

    df.describe(include="all").to_csv("reports/summary_statistics.csv")

    df.to_csv("output/final_dataset.csv",index=False)

    print("ETL Pipeline Completed")

In [ ]:
import os
os.makedirs("output", exist_ok=True)
run_etl_pipeline()

Number of Records: 5000
Number of Columns: 8
Raw data saved successfully!
ETL Pipeline Completed